# Generated by Django 2.0.5 on 2018-06-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_sub_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
    ]
