# Generated by Django 2.0.5 on 2018-06-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_sub_app', '0002_remove_signup_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
